services:
  - type: web
    name: gender_prediction_app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn gender_prediction.wsgi:application --bind 0.0.0.0:$PORT"
    autoDeploy: true
